version: '3.8'

services:
  base-builder:
    image: kanban-base:latest 
    build:
      context: .             
      dockerfile: Dockerfile.base 

  broker:
    image: eclipse-mosquitto:2.0
    container_name: mosquitto_broker
    ports:
      - "1883:1883"
    volumes:
      - ./broker/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - minha-rede

  suppliers:
    build:
      context: . 
      dockerfile: ./suppliers/Dockerfile 
    container_name: suppliers_service
    depends_on:
      - broker
      - base-builder 
    environment:
      - PYTHONUNBUFFERED=1 
    networks:
      - minha-rede

  warehouse:
    build:
      context: .
      dockerfile: ./warehouse/Dockerfile
    container_name: warehouse_service
    depends_on:
      - broker
      - base-builder
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - minha-rede
    volumes:
      - ./config/warehouse_config.json:/app/warehouse_config.json

  push-factor:
    build:
      context: .
      dockerfile: ./push-factory/Dockerfile
    container_name: push_factory_service
    depends_on:
      - broker
      - base-builder
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - minha-rede
    volumes:
      - ./config/push_factory_config.json:/app/push_factory_config.json
  
  pull-factory:
    build:
      context: .
      dockerfile: ./pull-factory/Dockerfile
    container_name: pull_factory_service
    depends_on:
      - broker
      - base-builder
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - minha-rede
    volumes:
      - ./config/pull_factory_config.json:/app/pull_factory_config.json

  manager:
    build:
      context: .
      dockerfile: ./manager/Dockerfile
    container_name: manager_service
    depends_on:
      - broker
      - base-builder
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - minha-rede
    volumes:
      - ./config/manager_config.json:/app/manager_config.json

  
  marketplace:
    build:
      context: .
      dockerfile: ./marketplace/Dockerfile
    container_name: marketplace_service
    depends_on:
      - broker
      - base-builder
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - minha-rede
    volumes:
      - ./config/marketplace_config.json:/app/marketplace_config.json

      
  master:
    build:
      context: .
      dockerfile: ./master/Dockerfile
    container_name: master_service
    depends_on:
      - broker
      - base-builder
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - minha-rede
    volumes:
      - ./data_summary/:/app/data_summary/

networks:
  minha-rede:
    driver: bridge
