version: '3.8'

services:

  broker:
    image: eclipse-mosquitto:2.0
    container_name: mosquitto_broker
    ports:
      - "1883:1883" 
    volumes:
      - ./broker:/mosquitto/config 
    networks:
      - minha-rede

  supplier:
    build: ./supplier 
    container_name: supplier_service
    depends_on:
      - broker 
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - minha-rede

  
  warehouse:
    build: ./warehouse 
    container_name: warehouse_service
    depends_on:
      - broker 
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - minha-rede
  

  push-factory:
    build: ./push-factory 
    container_name: push-factory_service
    depends_on:
      - broker 
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - minha-rede

  
  pull-factory:
    build: ./pull-factory 
    container_name: pull-factory_service
    depends_on:
      - broker 
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - minha-rede

  
  manager:
    build: ./manager 
    container_name: manager_service
    depends_on:
      - broker 
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - minha-rede

  
  marketplace:
    build: ./marketplace 
    container_name: marketplace_service
    depends_on:
      - broker 
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - minha-rede

  
  master:
    build: ./master 
    container_name: master_service
    depends_on:
      - broker 
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - minha-rede

networks:
  minha-rede:
    driver: bridge
